main_title : TrackVue
default_page_size : 30
diy_service_dir : service_logics
default_domain : System
default_lang : en-US
default_timezone : Seoul
default_date_format: '%Y-%m-%d'
default_datetime_format: '%Y-%m-%d %H:%M'
default_time_format: '%H:%M'
date_format: '%Y-%m-%d'
datetime_format: '%Y-%m-%d %H:%M'
time_format: '%H:%M'
shift_time_format: '%H:%M'
to_date_db_func : date
std_name : std
ops_name : ctl
default_lat : 37.381
default_lng : 127.11846
content_base_url : https://104.131.91.143/
#content_base_url : https://127.0.0.1/